//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type ActiveLocks struct {
	Schemaname         *string
	Relname            *string
	Locktype           *string
	Page               *int32
	Virtualtransaction *string
	Pid                *int32
	Mode               *string
	Granted            *bool
}
